# Generated by Django 2.2.1 on 2019-07-03 09:17

import apps.volunteer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='volunteer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=11)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.volunteer.models.volunteer.get_photo_path)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=5)),
                ('id_card', models.CharField(max_length=30)),
                ('visitdate', models.DateField()),
            ],
        ),
    ]
