# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-05 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elder',
            name='birthday',
            field=models.CharField(max_length=50),
        ),
    ]
