# Generated by Django 2.2.1 on 2019-07-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stranger_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=100)),
                ('upper_wear_fg', models.CharField(max_length=100)),
                ('cellphone', models.CharField(max_length=100)),
                ('orientation', models.CharField(max_length=100)),
                ('headwear', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('glasses', models.CharField(max_length=100)),
                ('bag', models.CharField(max_length=100)),
                ('upper_wear_texture', models.CharField(max_length=100)),
                ('lower_wear', models.CharField(max_length=100)),
                ('upper_color', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
