# Generated by Django 2.2.1 on 2019-07-04 07:38

import apps.camera.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stranger_log',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=apps.camera.models.stranger_log.get_path),
        ),
    ]
