# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-05 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_stranger_log_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='emotion_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('elder', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
