# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-06 08:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0006_area_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction_log',
            name='elder',
            field=models.CharField(default=datetime.datetime(2019, 7, 6, 8, 15, 25, 535283, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interaction_log',
            name='volunteer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
